Makefile
apps/api/src/applicant/dto/ienapplicant-job-create.dto.ts
apps/api/src/applicant/dto/ienapplicant-update-status.dto.ts
apps/api/src/applicant/ienapplicant.service.ts
apps/api/src/applicant/ienapplicant.util.service.ts
apps/api/src/common/logger.service.ts
master-table-seed.sql
package.json
packages/common/src/dto/ienapplicant-add-status.dto.ts
packages/common/src/dto/ienapplicant-job-create.dto.ts
packages/common/src/dto/ienapplicant-update-status.dto.ts

Added end-date for previous active status for select job/competition,
Added annotation for a job and milestone validation.

IEN-10 - enddate logic and validation message updated

---

apps/api/src/applicant/applicant.module.ts
apps/api/src/applicant/entity/ienhapcn.entity.ts
apps/api/src/applicant/entity/ienstatus-reason.entity.ts
apps/api/src/applicant/entity/ienusers.entity.ts
apps/api/src/applicant/external-api.controller.ts
apps/api/src/applicant/external-api.service.ts
apps/api/src/applicant/ien-master.controller.ts
apps/api/src/applicant/ien-master.service.ts
apps/api/src/common/external-request.ts
apps/api/src/database/database.module.ts
apps/api/src/migration/1648619359354-Add_column_in_HA_PCN.ts
apps/api/src/migration/1648639785227-add_table_status_reasons.ts
apps/api/src/migration/1648643525162-ienstatus_result_alter_pk.ts
apps/api/src/migration/1648658543531-alter_primary_key_user_and_ha.ts

- Add a module that fetches data from HMBC ATS URL, and saves it in our database.
- In this PR only consider Open API that does not require authentication.
- Change Primary Key auto generate to Primary key only for better upsert function with  ORM.

IEN-110 Import master table data from HMBC ATS to IEN app

---

apps/api/src/applicant/dto/ienapplicant-filter.dto.ts
apps/api/src/applicant/entity/ienapplicant-status-audit.entity.ts
apps/api/src/applicant/entity/ienapplicant-status.entity.ts
apps/api/src/applicant/external-api.service.ts
apps/api/src/applicant/ienapplicant.util.service.ts
apps/api/src/common/external-request.ts
apps/api/src/common/util.ts
apps/api/src/migration/1649654156768-unique_columns_in_status_audit.ts
apps/api/src/migration/1649659694208-add_column_in_applicant_status.ts
apps/api/src/migration/1649665454242-add_columns_in_applicant_status_audit.ts
apps/api/src/migration/1649687004734-alter_primary_column_from_integer_to_uuid_on_applicant_status_audit.ts
packages/common/src/dto/ienapplicant-filter.dto.ts
packages/common/src/ro/applicant.ro.ts

IEN-214 Sync milestone/status from HMBC ATS to IEN app and enable the status filter

IEN-214 Sync milestone/status from HMBC ATS to IEN app and enable status filter

---

apps/api/src/applicant/external-api.service.ts
apps/api/src/applicant/ienapplicant.service.ts
apps/api/src/applicant/ienapplicant.util.service.ts
packages/common/src/ro/applicant.ro.ts

- Update Applicant status.
- Name-wise search enhancement.

Update Applicant status, Name wise search enhance

---

Makefile
apps/api/src/applicant/applicant.module.ts
apps/api/src/applicant/ien-master.controller.ts
apps/api/src/applicant/ienapplicant.controller.ts
apps/api/src/auth/auth.constants.ts
apps/api/src/auth/auth.guard.ts
apps/api/src/auth/auth.module.ts
apps/api/src/auth/auth.service.ts
apps/api/src/common/auth.middleware.ts
apps/api/src/common/decorators.ts
apps/api/src/form/form.controller.ts
apps/api/src/form/form.module.ts
apps/web/src/components/Keycloak.tsx
apps/web/src/components/Pending.tsx
apps/web/src/pages/_app.tsx
apps/web/src/pages/applicants.tsx
apps/web/src/pages/details/[applicantId].tsx
apps/web/src/services/constants/roles.constants.ts
terraform/api.tf
terraform/cloudfront/response.js
terraform/secrets.tf

Added a roles guard
To create a new route, add both the UseGuards and the RouteAcceptsRoles decorators to your route. 
Also updated the response lambda function to accept responses from the new keycloak origin

IEN 209 implement roles guard

---

Makefile
apps/api/src/common/auth.middleware.ts
terraform/api.tf
terraform/cloudfront/response.js

Fixed CSP issue and fixed issue where AUTH_REALM was misspelled.

Ien 209 hotfix

---

apps/api/src/applicant/ienapplicant.controller.ts
apps/api/src/applicant/ienapplicant.service.ts
apps/web/src/components/display/AddRecordModal.tsx
apps/web/src/components/milestone-logs/recruitment/Milestone.tsx
apps/web/src/components/milestone-logs/recruitment/Record.tsx
apps/web/src/services/applicant.ts
apps/web/src/services/master-lists.ts

updated endpoint for retrieving a job based on job ID in order to update newly populated end date fields when a new milestone is added, also added conditional fields for offered position and candidate withdrew

add new endpoint, add conditional fields for new milestone

---

apps/web/src/components/display/ApplicantTable.tsx

remove table layout fixed class

remove fixed table layout

---

terraform/cloudfront/response.js

I forgot to add the test keycloak domain for response js.

Fixing response.js

---

apps/api/src/applicant/ienapplicant.controller.ts
apps/api/src/applicant/ienapplicant.service.ts
apps/api/src/applicant/ienapplicant.util.service.ts
apps/api/src/auth/auth.service.ts
apps/api/src/common/external-request.ts

put a restriction in add and edit status.
correct authentication and duplicate milestone error message.

IEN-252 put restriction in add and edit status

---

apps/web/src/components/display/AddRecordModal.tsx
apps/web/src/components/form/Field.tsx
apps/web/src/components/milestone-logs/Recruitment.tsx
apps/web/src/components/milestone-logs/recruitment/Milestone.tsx
apps/web/src/components/milestone-logs/recruitment/Record.tsx

IEN-269 - fix rendering jobs
IEN-271, IEN-272 - validate milestone start date and job post date

fix rendering jobs, validate job and milestone dates

---

apps/web/package.json
apps/web/src/components/Button.tsx
apps/web/src/components/display/AddRecordModal.tsx
apps/web/src/components/milestone-logs/recruitment/Milestone.tsx
apps/web/src/components/milestone-logs/recruitment/Record.tsx
apps/web/src/pages/details.tsx
apps/web/src/services/event-emitter.ts
yarn.lock

- fix adding milestones
- conditional button text 'update' and 'create' in add job modal
- fix add job modal's button style
- update applicant's last updated date when adding or updating milestones using **event emitter**

fix adding milestones, etc.

---

.sonarcloud.properties
apps/api/src/applicant/entity/ienusers.entity.ts
apps/api/src/applicant/ien-master.service.ts
apps/api/src/applicant/ienapplicant.controller.ts
apps/api/src/applicant/ienapplicant.service.ts
apps/api/src/applicant/ienapplicant.util.service.ts
apps/api/src/auth/auth.guard.ts
apps/api/src/common/auth.middleware.ts
apps/api/src/common/common.data.ts
apps/api/src/common/interface/EmployeeUser.ts
apps/api/src/common/interface/RequestObj.ts
apps/api/src/employee/employee.controller.ts
apps/api/src/employee/employee.entity.ts
apps/api/src/employee/employee.module.ts
apps/api/src/employee/employee.service.ts
apps/api/src/form/form.service.ts
apps/api/src/mail/mail.service.ts
apps/web/src/components/AuthContexts.tsx

- Enable added and updated by on status/milestone
- Restrict setting user access. ROLEADMIN is only set on the database and not set using API.
- Fix small amount of code smell from the sonar cloud list

IEN-287 enable added and updated by on status/milestone

---

apps/web/src/components/milestone-logs/Recruitment.tsx
apps/web/src/components/milestone-logs/recruitment/JobFilters.tsx

- apply filters right after each filter changes
- add `clear` button

IEN-277 | clear filters

---

Makefile
README.md
terraform/api.tf
terraform/db_backup.tf
terraform/sa.tf

* Adds terraform changes and instructions to restore a database from a backup

IEN-221 backup db

---

apps/api/src/report/report.service.ts

Applicants' registration report period-wise based on from and to date.

IEN-356 Generate Applicants registration report

---

apps/api/src/report/report.module.ts
apps/api/src/report/report.service.ts
apps/api/src/report/report.util.service.ts

- Update country-wise applicants count report
- Refine Applicant's count code as well

IEN-366 Report 2 country wise applicants count

---

apps/api/src/report/report.controller.ts
apps/api/src/report/report.service.ts
apps/api/src/report/report.util.service.ts

- Added API for reports 3 to 7
- APIs with fixed formate and partially confirmed Queries data

IEN-422 first version of apis for reports 3 to 7

---

Makefile
apps/web/src/services/report.ts

- added report 8
- added summary sheet
- changed app on dev to use FW keycloak

IEN-440 | download report 8

---

apps/web/cypress.json
apps/web/cypress/integration/4-reports/report.spec.ts
apps/web/src/components/index.tsx
apps/web/src/components/reporting/DataExtractReport.tsx
apps/web/src/components/reporting/index.tsx
apps/web/src/pages/reporting.tsx
apps/web/src/services/report.ts

need to find something for the formatting and add a validator for empty dates, but functionality is there

Ien 434 basic extract custom date

---

apps/api/src/applicant/applicant.module.ts
apps/api/src/applicant/entity/sync-applicants-audit.entity.ts
apps/api/src/applicant/external-api.controller.ts
apps/api/src/applicant/external-api.service.ts
apps/api/src/applicant/ien-master.service.ts
apps/api/src/applicant/ienapplicant.util.service.ts
apps/api/src/database/database.module.ts
apps/api/src/migration/1655454866799-addSyncApplicantsAuditTable.ts
apps/api/test/externalapi.e2e-spec.ts
apps/web/src/components/display/UploadFileModal.tsx

- IEN-443 Add table to log audit for applicant sync activity
- Add an end-point to fetch the last successful Audit run.
- Fix 5 Sonar MAINTAINABILITY points

IEN-443 Audit Sync Applicants run

---

apps/web/src/components/reporting/DataExtractReport.tsx
apps/web/src/services/report.ts

IEN-460 - prevent download of empty files and added toast to display reason
IEN-459, 462, 461 - added validation and error messages for when a user manually types in dates

bug fixes for ien 434

---

apps/api/src/report/report.controller.ts
apps/api/src/report/report.service.ts
apps/web/src/components/reporting/DataExtractReport.tsx
packages/common/src/dto/index.ts
packages/common/src/dto/report-period.dto.ts

added dto to make start and end date required for data extract

add dto for time period for data extract

---

apps/web/cypress/integration/5-user-management/change-role.spec.ts
apps/web/cypress/integration/5-user-management/search-users.spec.ts
apps/web/cypress/support/commands.ts
apps/web/cypress/support/index.ts
apps/web/src/components/SearchEmployee.tsx
apps/web/src/components/user-management/ChangeRoleModal.tsx
apps/web/src/components/user-management/UserFilter.tsx
apps/web/src/services/constants/roles.constants.ts

- fix missing pending option of user filter

IEN-472 | test revoke-access

---

apps/api/src/applicant/entity/ienusers.entity.ts
apps/api/src/applicant/external-api.service.ts
apps/api/src/applicant/ienapplicant.controller.ts
apps/api/src/applicant/ienapplicant.service.ts
apps/api/src/applicant/ienapplicant.util.service.ts
apps/api/src/common/interface/EmployeeUser.ts
apps/api/src/employee/employee.service.ts
apps/api/src/migration/1656487114336-ConvertUserIdIntegerToUUID.ts
apps/api/src/migration/1656503287019-converEmailColumToUnique.ts
apps/api/test/applicant.e2e-spec.ts
apps/api/test/fixture/ien.ts
apps/web/src/components/milestone-logs/recruitment/Milestone.tsx
packages/common/src/enum/organizations.ts
packages/common/src/ro/ien.ro.ts
scripts/data-employees.sql
scripts/data-milestones.sql

- Fetch HA from the list based on "organization". Apply filter on list applicant API based on HA.
- ien_users: make PK id as UUID so we can pull data from ATS + HA staff and use it as a reference in job and milestone-related activity.

IEN-465 enable HA onboarding in IEN app

---

apps/api/src/applicant/entity/ienjob.entity.ts
package.json
packages/common/src/dto/ienapplicant-job-create.dto.ts

Removed the `not empty` flag for Job Id 
Added UUID on before insert 
Also tweeked package log to accept more recent versions of node. My docker got wiped out and the current version of Node-alpine -16 will have Node v 16.16.0 installed (which will cause the application to exit because it's not 16.15.1.

IEN - 512 Job ID is nolonger mandatory

---

Makefile
apps/api/src/applicant/entity/ienjob.entity.ts
apps/web/src/components/display/AddRecordModal.tsx

Remove random job id before insert  statement

IEN - 544 Removed random job id

---

apps/api/src/applicant/dto/ienuser-filter.dto.ts
apps/api/src/applicant/entity/ienusers.entity.ts
apps/api/src/applicant/external-api.controller.ts
apps/api/src/applicant/external-api.service.ts
packages/common/src/enum/organizations.ts

does not include API key header as of yet

stub out user sync to ats

---

apps/web/src/components/display/ApplicantTable.tsx
apps/web/tailwind.config.js

- apply tailwind `jit` mode
- apply fixed layout to applicant table 
- show the first 8 characters of applicant_id or id of applicant
- truncate overflowing characters

IEN-584 | fix disappearing applicant table's ID sort button

---

apps/api/src/applicant/dto/ienuser-filter.dto.ts
apps/api/src/applicant/external-api.service.ts

re added to param, optional, so if from is entered and no 'to', will revert to current date instead

add to param to ats user sync

---

apps/api/src/applicant/external-api.controller.ts
apps/api/src/applicant/external-api.service.ts
apps/api/src/auth/jwt.guard.ts
apps/api/src/common/documentation.ts

Added a route to return all applicants (and related tables) 
Also added a JWT guard.

IEN 537 ats applicant sync

---

apps/web/src/components/display/AddRecordModal.tsx
apps/web/src/components/milestone-logs/recruitment/Record.tsx

fix prompt not showing when different HA tries to add more than one new job competition

IEN-620 - fixed already hired prompt

---

apps/api/src/applicant/external-api.controller.ts
apps/api/src/auth/jwt.guard.ts
terraform/api.tf
terraform/lambdafunction.tf
terraform/secrets.tf

Fixed guards on external api controller and added jwt secret to parameter store

IEN-537 continued - Fixed issues with jwt guard

---

apps/web/src/components/milestone-logs/Recruitment.tsx
packages/common/src/enum/milestone-status.ts

Job competition will only be green if there is no Candidate_was_not_selected status created after the job accepted status.

Ien 604 job completion remains green

---

apps/web/src/components/applicant/ApplicantMilestones.tsx

add check to show only recruitment if ha logged in

---

apps/api/src/applicant/external-api.controller.ts
apps/api/src/applicant/external-api.service.ts
apps/api/src/auth/jwt.guard.ts

Added expiry to tokens and added date filter to records

IEN - 537 continued 

---

apps/api/src/applicant/dto/ienapplicant-create.dto.ts
apps/api/src/applicant/ienapplicant.controller.ts
apps/api/src/applicant/ienapplicant.service.ts
apps/api/src/auth/auth.guard.ts

Check to see if token exists before passing it to getUserFromToken function. 
Made a bunch of checks null safe to avoid internal server errors.

Hotfix for internal server errors

---

apps/api/src/applicant/ienapplicant.service.ts
packages/common/src/helper/is-hired.ts

IEN-604 - fix hired banner on Details page and hired row on Manage Applicants page showing 'when candidate was not selected' option was added
IEN-636 - when HMBC user is logged in, show applicants latest milestone in process regardless of having accepted a job
* HA's will see Hired regardless of latest milestone of applicant, HMBC will see latest milestone

show latest milestone for hmbc users

---

apps/api/src/auth/jwt.guard.ts
apps/api/src/report/report.util.service.ts

Updated report 5 to only count the one license per applicant.

Ien 629 report differences

---

apps/api/src/applicant/external-api.controller.ts
apps/api/src/applicant/external-api.service.ts
apps/api/src/auth/jwt.guard.ts
scripts/generate-api-token.js

Split the query into steps. 
The first step fetches ids of applicants that have milestones updated within the to/from date fields. 
The second fetches all the applicants and related tables with those ids. 
Also updated the query params to use `IENUserFilterAPIDTO ` so to add pagination functionality to the query.

Ien 537 ats sync final updated (hopefully)

---

apps/api/src/report/report.service.ts
apps/web/cypress/integration/4-reports/report.spec.ts
apps/web/src/components/reporting/ReportTable.tsx
apps/web/src/pages/reporting.tsx

- changed default start date of standard reports from April 01, 2021 to May 02, 2022.
- moved standard report text to below Standard period Report heading

IEN-634 - change default start date for reports and move heading

---

apps/api/src/applicant/ienapplicant.util.service.ts
apps/web/src/components/applicant/ApplicantMilestones.tsx
apps/web/src/components/milestone-logs/MilestoneTable.tsx
apps/web/src/pages/applicants.tsx
apps/web/src/services/constants/milestone-logs.constants.ts

- also includes fix for landing tab for Applicant Details page

fix manage applicant page tabs not returning data

---

apps/web/cypress/integration/5-user-management/change-role.spec.ts
apps/web/cypress/support/commands.ts
apps/web/src/components/applicant/ApplicantProfile.tsx
apps/web/src/components/display/UserManagementTable.tsx
apps/web/src/components/user/UserRoles.tsx

- user status none to pending
- hide data-extract role
- remove country of education

IEN-672 IEN-682 IEN-683

---

apps/api/src/report/report.service.ts
apps/api/src/report/report.util.service.ts

I removed the `Applicant ID` column in the report because it was not being populated for most records. It also was a duplicate value. 
Otherwise the query looks to be working ok.

Removed redundant column

---

.config/.env-example
README.md
apps/api/README.md
apps/api/src/common/postToTeams.ts
apps/api/src/common/sendToSQS.ts
apps/api/src/notifylambda.ts
terraform/api.tf
terraform/notification_SQS_Lambda.tf
terraform/secrets.tf

changed webhooks to send to Teams channel instead of slack

IEN-671 change slack notifications to teams

---

apps/api/src/applicant/external-api.controller.ts
apps/api/src/applicant/external-api.service.ts
apps/web/cypress/integration/4-reports/report.spec.ts

I noticed some key information was missing from the RO for the applicants sync. I've added it here.

IEN-679 Added job and status to RO

---

apps/web/src/components/Search.tsx
apps/web/src/components/display/ApplicantTable.tsx
apps/web/tests/components/ApplicantTable.test.tsx

IEN-698 show milestone of applicant search results for hmbc and admin user

IEN-699 remove sort button of applicant id

---

apps/web/src/components/Search.tsx
apps/web/src/components/display/ApplicantTable.tsx

only hmbc user can see applicant's current milestone from search box

fix hired status for hmbc

---

apps/api/src/applicant/ienapplicant.util.service.ts
apps/api/src/report/report.util.service.ts

Reverted changes for previous IEN-708 branch, added extra column (updated_date) to order by

IEN 708 - revert prior 708 and update order by query

---

apps/web/src/components/milestone-logs/recruitment/Record.tsx

if start dates are the same, compare the updated date to get most recent milestone for job competition

IEN 725 - fix job competition status with same date milestone

---

docs/standard_report.md

- Updated dates and milestones in report document

IEN 729 - update report doc

---

apps/api/src/report/report.service.ts
docs/data_extract.md

added remaining phases to data extract

IEN 756 - added remaining phases to data extract

---

docs/standard_report.md

Added a few updates to the existing reports doc to match SQL queries and report data

IEN-779 - update existing report docs

---

apps/web/src/services/applicant.ts

Added null safety to AddMilestone response to prevent a second error pop up.

IEN 788 Added null safety to addMilestone request

---

apps/api/src/applicant/entity/ienapplicant.entity.ts
apps/api/src/applicant/external-api.service.ts
apps/api/src/common/util.ts
apps/api/src/migration/1676383627579-AddFlagForApplicantProcess.ts
packages/common/src/ro/applicant.ro.ts

add flag to differentiate between old and new process applicants

IEN-784 - add flag to sort old and new process candidates

---

Makefile
apps/api/src/report/report.controller.ts
apps/api/src/report/report.service.ts
apps/api/src/report/report.util.service.ts
apps/web/src/services/report.ts

added new column for new process applicants

IEN-785 - add new column for new process applicants

---

apps/web/cypress/support/commands.ts
apps/web/src/components/display/AddRecordModal.tsx

To complete this I just added the "IsClearable" flag to the department field

IEN-807 Adding the Clear Option To the Add Job Record Form

---

apps/api/src/applicant/external-api.service.ts
apps/api/src/applicant/ienapplicant.util.service.ts
apps/api/src/migration/1678229862052-AddUniqueIndexToAuditOnApplicantStatus.ts

- insert milestones of new applicants
- do not insert the same milestone without start_date for an applicant

IEN-819 insert milestones of new applicants

---

apps/api/src/cachereportfour.ts
apps/api/src/cachereports.ts
apps/api/src/database/database.module.ts
apps/api/src/migration/1678219888032-AddTableToCacheReport4.ts
apps/api/src/ormconfig.ts
apps/api/src/report/entity/report-cache.entity.ts
apps/api/src/report/report.controller.ts
apps/api/src/report/report.service.ts
apps/api/test/04-report-4.e2e-spec.ts
apps/api/test/report-request-util.ts
apps/web/src/components/reporting/ReportTable.tsx
packages/common/src/interfaces/period-filter.ts
terraform/lambdafunction.tf
terraform/main.tf
terraform/report_lambda_function.tf

add cron job, add report_cache migration, change report 4 to select from cached table depending on period

IEN -818 - add cron job, add report_cache migration, modify report 4 endpoint

---

apps/api/src/migration/1678729486448-AddApplicantIdFkToStatusAudit.ts
packages/scripts/src/generate-milestones.ts

- Create applicants
- Create milestones to distribute applicants evenly over each stage.
- Randomly skip milestones

Seed test data

---

apps/web/src/components/applicant/ApplicantProfile.tsx
apps/web/src/components/display/AddApplicantModal.tsx

Changed `Permanent Resident Status` to `Immigration Status` in Applicant Details tombstone

IEN-778 - change permanent resident text to immigration status

---

apps/api/package.json
yarn.lock

- axios dependency got removed from @nestjs/common upgrade, reinstalled it

install axios in api folder

---

Makefile
apps/api/package.json
apps/api/src/admin/admin.controller.ts
apps/api/src/admin/admin.module.ts
apps/api/src/admin/admin.service.ts
apps/api/src/admin/dto/upload.dto.ts
apps/api/src/admin/ro/upload.ro.ts
apps/api/src/admin/ro/user-guide.ro.ts
apps/api/src/app.module.ts
apps/api/src/common/documentation.ts
apps/api/src/common/logger.service.ts
apps/api/src/common/sendToSQS.ts
apps/api/src/migration/1684340041778-AddAdminAccess.ts
apps/api/src/report/entity/report-cache.entity.ts
apps/api/src/report/report.service.ts
apps/web/src/services/event-emitter.ts
apps/web/src/services/index.ts
packages/common/src/enum/access.ts
packages/common/src/ro/index.ts
packages/common/src/ro/user-guide.ts
terraform/api.tf
terraform/bastion.tf
terraform/docs.tf
terraform/variable.tf
yarn.lock

IEN-841 add user guide pdf to portal

---

apps/api/src/admin/admin.controller.ts
apps/api/src/admin/admin.service.ts
apps/api/src/admin/ro/user-guide.ro.ts
apps/web/src/components/Disclosure.tsx
apps/web/src/components/admin/HeaderHelper.tsx
apps/web/src/components/admin/UserGuideList.tsx
apps/web/src/components/admin/UserGuideRow.tsx
apps/web/src/services/admin.ts
packages/common/src/ro/user-guide.ts

- Add API endpoints
- to get versions of a file
- to delete a version or a file
- to restore a file to a version
- Add `version` option to the download endpoint 
- Use `Disclosure` to display versions

IEN-842 list user guide versions

---

apps/api/src/admin/admin.service.ts
apps/web/src/components/admin/UserGuideRow.tsx

- remove the delete button from the list in the header component

fix user guide bucket name

---

apps/api/src/applicant/dto/ienapplicant-add-status.dto.ts
apps/api/src/applicant/dto/ienapplicant-update-status.dto.ts
apps/api/tsconfig.json

- Runtime.ImportModuleError
- add `preserveSymlinks` compiler option

IEN-862 add preserveSymlinks compiler option

---

apps/api/src/applicant/dto/ienapplicant-filter.dto.ts
apps/api/src/applicant/entity/ienapplicant.entity.ts
apps/api/src/applicant/ienapplicant.controller.ts
apps/api/src/applicant/ienapplicant.service.ts
apps/api/src/applicant/ienapplicant.util.service.ts
apps/api/src/migration/1688139286025-AddActiveInactiveFlagToApplicantsTable.ts
apps/web/src/components/ToggleSwitch.tsx
apps/web/src/components/applicant/ApplicantProfile.tsx
apps/web/src/components/display/ApplicantTable.tsx
apps/web/src/components/user/UserDetails.tsx
apps/web/src/components/user/UserRoles.tsx
apps/web/src/pages/applicants.tsx
apps/web/src/services/applicant.ts
packages/common/src/ro/applicant.ro.ts

- added checkbox to hide Inactive applicants from manage applicants table
- added toggle on applicant details page to switch active flag between active and inactive
- add `is_active` flag to applicant table
- this is just preliminary work, with the assumption of future discussions to add logic and determine what makes an applicant `inactive`
[IEN-844](https://eydscanada.atlassian.net/jira/software/c/projects/IEN/boards/272?modal=detail&selectedIssue=IEN-844)

IEN-844 - preliminary hide inactive and active/inactive applicant toggle

---

apps/web/src/components/milestone-logs/recruitment/MilestoneForm.tsx

Fixed an issue where the id of a milestone was being sent to the backend instead of the name.

Ien hotfix referral status not found

---

apps/api/src/applicant/dto/ienapplicant-filter.dto.ts
apps/api/src/applicant/ienapplicant.util.service.ts
apps/web/cypress/e2e/6-ha/inactive-active-applicants.spec.ts
apps/web/src/components/applicant/ApplicantProfile.tsx
apps/web/src/pages/applicants.tsx

Updated copy to change "inactive"/"active" users into hidden vs visible. 
Updated the name of the filter param to match. 
Updated the default value of the toggle in the manage applicants page to make sense with the new wording.

Updated copy and function prior to launch

---

Makefile
apps/api/package.json
apps/api/src/applicant/external-api.controller.ts
apps/api/src/applicant/external-api.service.ts
apps/api/src/applicant/ien-master.controller.ts
apps/api/src/applicant/ienapplicant.controller.ts
apps/api/src/common/error-exception.filter.ts
apps/api/src/common/external-request.ts
apps/api/src/database/database.module.ts
apps/api/src/employee/employee.controller.ts
apps/api/src/form/form.controller.ts
apps/api/src/mail/mail.service.ts
apps/api/src/syncdata.ts
apps/web/src/pages/404.tsx
terraform/iam.tf
terraform/lambdafunction.tf
terraform/secrets.tf
terraform/ses.tf

- deploy AWS SES
- add `mail_recipients` to parameter store: list of email addresses separated by comma
- notify failures
- through the Teams channel by logging error
- through email using SES

IEN-865 notify the failure of syncing with ATS

---

apps/api/src/applicant/ienapplicant.util.service.ts

- Parameterize query to avoid SQL injection

IEN-867 fix applicants query

---

.config/.env-example
.gitignore
apps/api/src/migration/1695251583963-RemoveReportRoleFromHA.ts
apps/web/src/components/user/UserRoles.tsx

- Remove the reporting role from HA users
- Hide the button assigning the reporting role on the user details page

IEN-876 remove reporting role from HA users

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml
.github/workflows/deploy-test.yml
.github/workflows/pr-check-tf.yml
apps/web/src/components/applicant/ApplicantProfile.tsx
apps/web/src/utils/applicant-utils.ts

IEN-878 show country of education in the educations field

---

apps/api/src/applicant/ienapplicant.service.ts
apps/api/src/migration/1702335836108-AddGenericNursingEducation.ts
apps/api/test/report-util.ts
apps/web/src/utils/applicant-utils.ts
master-table-seed.sql

Fixed an import issue
Changed the label for educations from the BCCNM

IEN patch add generic education fix import

---

apps/api/src/applicant/external-api.controller.ts
apps/api/src/applicant/external-api.service.ts
apps/api/src/syncdata.ts

Added a parameter to add paginations. 
This will allow us to do partial syncs and locate the failing records.

Ien add pagination to sync

---

apps/api/src/report/report.util.service.ts

Ticket: https://eydscanada.atlassian.net/browse/IEN-889
- Select reason column in extract milestone

IEN-889 | add reason to spreadsheet

---

terraform/cloudfront/response.js

PR reference from TBCM: https://github.com/bcgov/MOH_TeamBasedCare/pull/184

[IEN-905] ZAP scan fix - added permissions policy header

---

.github/workflows/ci-zap.yml

Ref: https://github.com/zaproxy/action-full-scan

IEN-893 | upgrade zapscan docker to latest version

---

Makefile
apps/api/src/common/decorators.ts
apps/api/src/report/report.controller.ts
apps/api/src/report/report.module.ts
apps/api/src/report/report.service.ts
apps/api/src/report/report.util.service.ts
apps/web/src/components/AuthContexts.tsx
apps/web/src/pages/reporting.tsx
docker-compose.yml

Ticket: https://eydscanada.atlassian.net/browse/IEN-874
- fix docker-compose env
- Add `ha_pcn_id` to filter report milestone data
- Add `abbreviation` to filter report applicant data
- HA Users hide period report

IEN-874  | HA Report filter by user's HA

---

terraform/api.tf
terraform/db.tf
terraform/lambdafunction.tf
terraform/main.tf
terraform/notification_SQS_Lambda.tf
terraform/report_lambda_function.tf

Fixes: 
Updated all lambda function runtimes to be nodejs18x. 
Updated aws terraform version to version 4. 
Updated RDS database sizes to be smaller, t3 mediums instead of r5 larges.

IEN Terraform updates 

---

apps/web/jest.config.js
apps/web/package.json
apps/web/src/components/display/AddApplicantModal.tsx
apps/web/src/components/display/AddRecordModal.tsx
apps/web/src/components/milestone-logs/recruitment/MilestoneForm.tsx
apps/web/src/components/reporting/DataExtractReport.tsx
apps/web/src/utils/dto-validator.ts
apps/web/tsconfig.json
packages/common/package.json
yarn.lock

Follow PR: https://github.com/bcgov/MOH_TeamBasedCare/pull/183
- remove class-validator-formik; 
- add customize validator;

IEN-893 | Subtask IEN-908 | Dangerous JS function fix

---

apps/api/src/applicant/dto/sync-applicants-result.dto.ts
apps/api/src/applicant/external-api.controller.ts
apps/api/src/applicant/external-api.service.ts
apps/api/src/syncdata.ts
terraform/lambdafunction.tf

Re-added sync. It looks like the data in the sync has been restored. 
Added a function to run the sync as a smaller syncs instead of a single 
I have wrapped this feature in a flag, so it will be disabled by default.

Ien sync prototype fix

---

apps/api/src/admin/dto/bccnm-ncas-update.dto.ts
apps/api/src/applicant/external-api.service.ts
apps/api/src/syncdata.ts

Having a row without a country of education was blocking the sheet upload. 
I also needed to make some small tweaks to the sync.

Made country of education optional, made tweak to sync

---

apps/web/cypress/e2e/4-reports/report.spec.ts
apps/web/src/pages/reporting.tsx
terraform/report_lambda_function.tf

- comment out cron; 
- remove report table;
- Remove no longer needed testing cases, found by github action failure

IEN-897 | Remove the “Standard Period Report”

---

apps/api/src/applicant/external-api.service.ts

Fixed an issue where the last user in the sync would not be upserted.

Fixed off by one error found in sync

---

apps/api/src/migration/1727287611192-DeleteNonuseNHCommunities.ts

- Have tested locally and double check with the original list. (https://eydscanada.atlassian.net/browse/IEN-903)

IEN-914 | Remove communities from Northern Health Authority that are not on the list.

---

apps/web/src/components/admin/hooks/useSessionStorage.tsx

- We remove cleaner function, somehow when it refreshes, it triggers the cleaner function.
- Deployed to TEST and verified with more than 5 mins, working fine now.

IEN-930 | [QA Sent back] | Automatic page refresh is clearing BCCNM upload data

---

apps/api/src/admin/admin.service.ts
apps/api/test/13-bccnm-ncas-update.e2e-spec.ts
apps/web/cypress/e2e/7-admin/bccnm-ncas-update.spec.ts
apps/web/src/components/admin/BccnmNcasPreview.tsx
apps/web/src/components/admin/BccnmNcasUpdateFilter.tsx

- fix invalid & no changes
- update wording from "no updates" to "no changes" from backend.
- fix e2e testing
- Invalid
- No changes

IEN-936 | BCCNM preview filter bug

---

apps/api/src/applicant/endofjourney.service.ts
apps/api/src/applicant/entity/ienapplicant.entity.ts
apps/api/src/applicant/external-api.service.ts
apps/api/src/applicant/ien-master.service.ts
apps/api/src/applicant/ienapplicant.util.service.ts
apps/api/src/migration/1732042370374-AddEndOfJourneyToIenApplicants.ts
apps/api/src/migration/1732043239738-UpdateWithdrawToNotProceedingStatus.ts
apps/api/src/report/report.util.service.ts
apps/api/src/report/types/milestone-table-entry.ts
apps/web/src/components/applicant/ApplicantProfile.tsx
apps/web/src/components/display/ApplicantTable.tsx
apps/web/src/components/milestone-logs/Recruitment.tsx
packages/common/src/enum/milestone-status.ts
packages/common/src/ro/applicant.ro.ts

- Add Journey Incomplete
- Fix Journey Complete
- Fix report
- Add migration to update milestone status from "withdraw" to "not proceeding"
- Add migration to new column "end_of_journey" flag

IEN-918 | Journey Incomplete; Fix Journey Complete; Fix Report;

---

apps/api/src/applicant/endofjourney.service.ts
apps/api/src/applicant/entity/ienapplicant.entity.ts
apps/api/src/endofjourney.ts
apps/web/src/components/applicant/ApplicantProfile.tsx

- Fix db connection issue, no more error log.
- Add "End of Journey" to UI for easier reading the flag of applicant.

IEN-912 | Journey Complete

---

apps/api/src/applicant/ienapplicant.util.service.ts
apps/web/src/components/display/ApplicantTable.tsx

Deployed to TEST and verified.

IEN-955 | Archive PII deleted candidates for Health Authorities

---

apps/web/src/components/applicant/ApplicantProfile.tsx

Added a message for when an applicant is deleted.

IEN -961 Added missing message for deleted applicants

---

terraform/cloudfront.tf
terraform/main.tf

Updated the terraform configuration to account for the domain change.

Update tf config

---

terraform/network.tf

Update config after AWS terraform version upgrade

JSU-55: Update aws_subnet_ids -> aws_subnets

---

apps/api/src/employee/employee.service.ts

Fix for JSU-410: Sorting by role

Bugfix for JSU-410

---

apps/web/src/pages/_app.tsx

Add axios response interceptor to handle alternate lambda serialization

JSU-408: Add axios response interceptor for Lambda runtime

---

apps/api/package.json
yarn.lock

Downgrade express to latest 4.x

JSU-408: Downgrade express to 4.19.2

---

apps/api/src/app.config.ts
apps/api/src/common/interceptors/request-logging.interceptor.ts

Add interceptor for request logging

Jsu 408 req log

---

apps/api/src/app.config.ts
apps/api/src/common/interceptors/request-transform.interceptor.ts

Attempt to parse incoming request bodies if they're a Buffer as opposed to a regular JSON object.

JSU-408: Parse incoming message body if Buffer

---

.github/workflows/pr-check-pa11y.yml

createComment is moved under the .rest. now.

Fixing the Issue generation from the GitHub Action
