terraform/cloudfront.tf, terraform/main.tf
This links the cloud front distributions for dev/test to freshworks.club domains and adds ssl certs. The DNS records for the .club domain are on Freshwork's aws and the certifcates were created manually in LZ2. 
Note: I've already applied these both to dev and test. 
Big thanks to Vyas for helping me get this to work.
=> Added .club domains for dev and test

Makefile
While testing out my work on keycloak I noticed my changes to the web app were not being reflected.
It looks like `make deploy app` was just invalidating the cloudfront distribution. `sync-app` should actually deploy the front end.
=> Fixed app deployment

apps/api/src/migration/1651041828909-updateseeddata.ts, apps/web/src/components/milestone-logs/MilestoneTable.tsx
Added "Party" column in seed milestone/status data.
We will receive the "Party" field from the HMBC ATS code for all the 4 main categories "Intake" "license/Registration", "BC PNP" and "Final.
This code will fix one existing "security hotspot" in sonar cloud too (for this line "status.split(/\s+-\s+/, 2);").
=> Add party field in existing seed status/milestone data

apps/web/src/services/date-utils.ts
this seems more like a quick fix to me, I'm not sure at the moment what else to do with this.  I left a comment above the change, but it's basically comparing the start_date from the last milestone to the current date, excluding time values
=> show word Today for competition duration being added on current date

apps/web/src/pages/applicants.tsx
when using page options in a tab, ex All and setting items per page to anything besides default, going to last page then switching tabs, the requests would include the amount skipped from the previous request, skipping over items inside Intake tab, so I just set the page Index back to 1 when changing tabs
=> fix for tab requests using previous skip value

apps/web/cypress/integration/6-ha/ha-user.spec.ts, apps/web/src/components/applicant/ApplicantContext.tsx, apps/web/src/components/milestone-logs/MilestoneTable.tsx, apps/web/src/pages/applicants.tsx
- disable editing milestones outside of recruitment
- hide 'add applicant' button
- order milestones by start date and id
=> IEN-578 disable editing milestones outside of recruitment

yarn.lock
I was able to update 3 of the 5 packages flagged by dependabot. Dice and class-validator both have unresolved vulnerabilities.
=> Yarnlock updated

apps/web/src/components/form/DatePickerField.tsx
JS Date object with yyyy-MM-dd formatting causes it to be reduced by 1 day.  dayjs and toDate corrects this
=> fix selected value for date picker

apps/web/src/components/reporting/DataExtractReport.tsx
re ordered the max date check for the datapicker on Data Extract, was previously giving the current value picked priority
=> IEN 707 - reorder max date check for data extract

apps/api/src/report/report.util.service.ts
I figured since we're already getting these counts at the beginning of the query and reusing them for the total count, to just to reuse them in the query again for each
=> IEN 708 - fix licenses count in report 4

apps/api/src/migration/1676577091787-RemoveOldUnusedTables.ts
removes unused tables created during initial project setup
Note: only `form` and `submission` were found in dev, test and prod.  The other applicant tables seem to just be outliers in some local environments
=> IEN-798 - migration to remove old unused tables

.github/workflows/pr-check-e2e.yml, .github/workflows/pr-check-pa11y.yml, apps/web/cypress.json, apps/web/src/components/applicant/ApplicantContext.tsx
Looks the `ubuntu-latest` default Node version changed recently to >17.x, even looks like its changing to 18.x soon ([here](https://github.com/actions/runner-images/issues/7002)).  The current Cypress version we use, 9.6.0 is only compatible with Node versions 12.x, 14.x and 16.x.  Could be a quick fix for now, unsure of any major changes trying to upgrade Cypress right now
=> IEN 805 - fix cypress action failures

apps/api/src/applicant/entity/ienusers.entity.ts, apps/api/src/applicant/external-api.service.ts, apps/api/src/migration/1677871799880-DropUserIndexOnEmail.ts
- remove the unique index on `user_id` <- it should be enforced by ATS
- use the unique index on `email` as a unique constraint to upsert users
=> IEN-812 fix sync user with ATS

.github/workflows/ci-zap.yml, .github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml, .github/workflows/deploy-test.yml, .github/workflows/pr-check-api.yml, .github/workflows/pr-check-common.yml, .github/workflows/pr-check-e2e.yml, .github/workflows/pr-check-pa11y.yml, .github/workflows/pr-check-tf.yml, .github/workflows/pr-check-web.yml, apps/api/test/04-report-4.e2e-spec.ts
Was able to get the warning resolved for all but one in ZAP. Made the versions all the most recent for the ci-zap file. Found someone mentioning this issue in the GitHub repo for the action. They show that they updated to node 16 and suggest all action runs are displaying this and show where they updated.
=> IEN-810 Resolve GitHub actions warnings

apps/api/src/applicant/external-api.service.ts, apps/api/src/common/external-request.ts
The ATS sync has been broken for several days. The changed the format of their api, and issued new API keys. 
This PR updates the format of the affected routes.
=> IEN Hotfix - update ATS sync url format 

Makefile, apps/api/src/migration/1699550484811-RemoveDuplicateMilestone.ts
The Foreign key referenced in this migration already existed in test, causing the migration to fail and the application to stop functioning. 
Before creating the foreign key, I added a check to see if it already exists.
=> Updated migration to only conditionally create the foreign key

apps/api/src/applicant/external-api.controller.ts, apps/api/src/applicant/external-api.service.ts, apps/api/src/common/external-request.ts
The sync on test failed when the reasons api started returning an empty array. 
If the ats api returns an empty array, the script will now skip the upsert step.
=> Fixed issues with sync encountering empty arrays

apps/api/src/applicant/external-api.service.ts
These are some quality of life changes to the sync. 
I used this code to help debug the issue with the sync. 
- Fixed for loops for segmented inserts
- Changed the insertion size to 250 to match the batch size of the fetch from ATS 
- Results.raw was returning undefined. I switched to counting the identifiers instead
- Switched the try catch location around the milestone upsert so that if/when it fails, it will fail more gracefully. 
- Fixed issue where latest status was not being properly updated. 
- Fixed user upsert counts
=> IEN Sync fixes and polish

apps/api/src/migration/1720633134664-UpdateNHCommunities.ts
Ticket: https://eydscanada.atlassian.net/browse/IEN-903
- Add new communities in North Health
- I have tested locally with this migration, also tested migration:revert
- For the community not listed in ticket IEN-903, I discussed with Ram that the existing community will remain in place to avoid any negative impact. That's why I only have "insert" script.
- Screenshot of local database
=> IEN-903 | add new communities in HA NorthHealth

apps/web/src/components/UserDropdown.tsx
- can simply use `window.location.origin` as `redirect_uri`
- call `removeUser` function
- I actually did run `make tag-test` and it is working fine on TEST
=> IEN-898 | Logout Bug invalid redirect url

apps/api/src/report/report.service.ts, apps/api/src/report/report.util.service.ts, apps/web/src/pages/_app.tsx
Updated data extracts. For HA users, only users who have a "referred to " milestone will have their milestones extracted. 
I added two steps to the process. The first takes the users HA PCN and finds the id of the "Applicant Referred to " milestone for that HA. The second selects a list of ids of users who have that milestone. 
The remainder is the main query, just with a check to ensure that only milestones from those users are selected.
=> Added HA specific extracts for both milestone and applicant extracts

terraform/report_lambda_function.tf
- It turns out comment out the `schedule_expression` failed deployment.
- So we add `count = 0` instead to disable it. And by using `count`, we have to add `[count.index]`.
I have verified by deploying this PR to DEV and see from the AWS console.
=> IEN-897 | Disable the period report cron job

Makefile, apps/api/src/report/report.controller.ts, apps/api/src/report/report.module.ts, apps/api/src/report/report.s3.service.ts, apps/web/src/services/report.ts, terraform/api.tf, terraform/cloudfront/response.js, terraform/reports_s3.tf, terraform/variable.tf
- Add new S3 bucket to save the large json
- Lambda upload json to S3 and return pre-signedUrl to frontend to download
- Only when data length is more than 10 and not in local and test env would use s3 to download the file
I did deploy to TEST and works fine.
- it has 22133 rows
=> IEN-885 | Fix Report Large Response issue

apps/api/src/migration/1727200471805-AddBackReportRoleToHA.ts, apps/web/src/components/user/UserRoles.tsx
- Add back the report permission to HA user.
- It's most of the revert of this past PR (https://github.com/bcgov/internationally-educated-nurses/pull/592/files)
- The query inserts all HA employees without "reporting" role.
- Have tested locally
- The report already only download the associated organization
(Login myself as Fraser Health Authority)
=> IEN-923 | Enable HA Report Permission

apps/api/src/common/feature-flag.service.ts, apps/api/src/employee/employee.module.ts, apps/api/src/employee/employee.service.ts, terraform/iam.tf, terraform/secrets.tf
After digging more, I decide to use `parameter store` with `dynamic fetch the parameter` in api so that in the future we don't encounter terraform state inconsistent and easier to add more other feature flags.
- Because it's hard to add feature flag to the migration(previous enable HA PR: https://github.com/bcgov/internationally-educated-nurses/pull/656), so we implement this in api level to filter user role if it's HA user and with reporting role.
- If in local env, ignore the parameter store and always return true
- Have deployed to DEV and verified.
- Tested redeploy terraform not override the existing value
- Tested the feature flag functionality by toggling the value in parameter store
- lambda can read the parameter
- parameter store
=> IEN-928 | Add Feature Flag to HA access Report

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml, .github/workflows/deploy-test.yml, .github/workflows/pr-check-tf.yml, Makefile
- Added `@TF_LOG=DEBUG terraform...` to makefile and see the log on github action, found that it shows `terraform command not found`
- I can not find why `ubuntu-latest` removed `terraform` on github action.
- Add https://github.com/hashicorp/setup-terraform to github action.
=> IEN HOTFIX | terraform command not found on github action env

.github/workflows/deploy-dev.yml, .github/workflows/deploy-test.yml, apps/web/cypress/support/commands.ts, apps/web/src/components/Pagination.tsx, apps/web/src/components/admin/BccnmNcasPreview.tsx, apps/web/src/components/admin/BccnmNcasSection.tsx, apps/web/src/components/admin/hooks/useSessionStorage.tsx
- add `sessionStorage` to avoid reload clean; 
- modify page size to `5, 10 , 30, 50, 100`; (we keep `5` because of e2e testing using 5)
- fix the previous terraform PR formatting issue to avoid the WebPR github action failure (previous PR did not have web change, hence not trigger the WebPR github action)
Have deployed to TEST and verified.
- can also verify by manually refreshing the page by clicking the refresh button on the browser.
- page size did exist before but modified to ideal number
=> IEN-930 | IEN-938 | Automatic page refresh is clearing BCCNM upload data | Add variable pagination to the BCCNM/Inspire data review page

apps/web/src/components/FileUploader.tsx
- Add file size 6MB restriction
- Refactor the existing code: Don't need to check extension as `react-dropzone` returns empty file if the ext is not correct.
Deployed to TEST and verified.
- When the ext is not correct
- When file size > 6MB
=> IEN-937 | Add restriction to BCCNM spreadsheet file upload

apps/web/src/components/milestone-logs/recruitment/MilestoneForm.tsx, apps/web/src/utils/applicant-utils.ts
- refactor filter condition; 
- and add new condition: Ha user does not have withdraw option
- Admin able to see withdrew:
- Ha user not able to see withdrew:
=> IEN-919 | End of Journey - Remove HA ability to mark candidate as Withdrew form competition

apps/api/src/report/report.util.service.ts, apps/web/src/services/report.ts
- add `End of Journey` column to `milestone` extract with the following logic
```ts
/**
* The `endOfJourneyColumn` defines a CASE statement that evaluates the journey status of an applicant.
* It checks the `ien_applicant_status_audit` and `ien_applicant_status` tables to determine whether the applicant
* has reached either 'End of Journey - Journey Complete' or 'End of Journey - Journey Incomplete' status.
*
* Logic:
* - If there exists a record with 'End of Journey - Journey Complete' for the same `applicant_id`, the column
*   is set to 'End of Journey - Journey Complete'.
* - If no 'Journey Complete' record is found but a 'Journey Incomplete' record exists, the column is set to
*   'End of Journey - Journey Incomplete'.
* - If neither status exists for the applicant, the column value …
```
=> IEN-920 | End of Journey Report

apps/api/src/applicant/endofjourney.service.ts, apps/api/src/applicant/ienapplicant.service.ts, apps/web/package.json, apps/web/src/components/milestone-logs/system/SystemForm.tsx, apps/web/src/components/ui/calendar.tsx, apps/web/src/components/ui/form.tsx, apps/web/src/components/ui/scroll-area.tsx, apps/web/src/components/ui/select.tsx, yarn.lock
- Fix milestone select validation
- Fix title when update milestone
- Fix calendar UI/UX
- Fix EoJ flag not being updated after CRUD re-engaged milestone
=> IEN-941 | QA fix

.github/workflows/ci-zap.yml, .github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml, .github/workflows/deploy-test.yml, .github/workflows/pr-check-api.yml, .github/workflows/pr-check-common.yml, .github/workflows/pr-check-e2e.yml, .github/workflows/pr-check-pa11y.yml, .github/workflows/pr-check-tf.yml, .github/workflows/pr-check-web.yml
GitHub is removing version 3 of [upload-artifact](https://github.com/actions/upload-artifact) and [download-artifact](https://github.com/actions/download-artifact) by Jan 30, 2025. Update workflows to use version 4.
- We updated the related packages to version 4 and adjusted zap-scan to accommodate the changes in version 4.
- update checkout@v4
- update cache@v4
- update setup-node@v4
- update zap-scan@0.12.0
=> IEN-947 | update github action checkout and related to v4

apps/api/src/applicant/ienapplicant.util.service.ts, apps/api/src/common/search-names.ts, apps/web/src/components/Search.tsx, apps/web/tests/components/form/Search.test.tsx
- Reuse the same search UI
- Add ATS1_ID to display in search result table
- Will search the ATS1_ID if the search wording is number string & length = 6.
- Fixed related unit-testing
=> IEN-949 | Search ATS1_ID

apps/api/src/migration/1736304205932-UpdateApplicantStatusFromNCASToInspire.ts, apps/web/src/components/admin/BccnmNcasSection.tsx, packages/accessibility/src/pa11y-ci.js, packages/common/src/constants/index.ts, packages/common/src/constants/ncas.constants.ts, packages/common/src/enum/milestone-status.ts
- update status name from ncas to inspire in milestone table
- update ui on Admin page
- Fix broken a11y workflow (copied same fix from EHPR)
- In an enum, we cannot use variables, so we must use plain string values. That’s why we didn’t use the variable `NCAS_NEW_NAME` from `@ien/common`.
=> IEN-939 | rename ncas to inspire (from user perspective)  IEN-954 | Fix broken a11y workflow

apps/api/src/applicant/applicant.module.ts, apps/api/src/applicant/entity/ienapplicant.entity.ts, apps/api/src/applicant/entity/ienapplicant.subscriber.ts, apps/api/src/applicant/ienapplicant.controller.ts, apps/api/src/applicant/ienapplicant.service.ts, apps/api/src/common/scramble.service.ts, apps/api/src/database/database.module.ts, apps/api/src/migration/1737077728589-AddDeleteInfoAndBackupToIenApplicants.ts, apps/web/src/components/Button.tsx, apps/web/src/components/applicant/ApplicantProfile.tsx, apps/web/src/services/applicant.ts, packages/common/src/ro/applicant.ro.ts
- Added new columns to the `ien_applicants` table:
- `deleted_by_id` (UUID, nullable)
- `deleted_date` (timestamp, nullable)
- `backup` (JSONB, nullable, default: null)
- Implemented data deletion in the backend, including functionality to scramble personally identifiable information (PII).
- Introduced a deletion date and corresponding button to the frontend interface.
- Added `subscribers` to prevent ATS update the scramble info if applicant was deleted
- Before Deletion
- Deleting
- After Deletion
=> INE-951 | Delete Applicant (Scramble PII)

apps/api/src/applicant/entity/ienapplicant.subscriber.ts
- **Bug Fix**: Resolved an issue with ATS sync where scrambled data was being overwritten unexpectedly.
- After QA testing in the `TEST` environment, it was discovered that the `upsert` operation is being treated as an `insert` event rather than an `update` event.
=> IEN-951 | Delete Applicant | QA Bug fix

apps/api/src/applicant/external-api.service.ts
- After QA, found that ATS would override the database
=> IEN-939 | QA fixed | Rename NCAS to Inspire

apps/api/src/applicant/ienapplicant.controller.ts, apps/api/test/fixture/ien.ts
- The error occurs because in AWS Lambda environment, certain array data gets treated as a Uint8Array rather than a regular JavaScript array. When the global ValidationPipe with [whitelist: true] tries to process this data, it attempts to delete properties from the Uint8Array, which is not allowed since Uint8Array indexed properties are immutable.
- Adding job_location to e2e test
- Updating indexOf() to includes() as per SonarQube suggestion
=> JSU-408: Fixing "Cannot delete property '0' of [object Uint8Array]" issue on AWS due to AWS considering int[] as Uint8Array(file data)
